FROM cypress/included:15.5.0

# Establecer directorio de trabajo
WORKDIR /e2e

# Copiar los archivos de test y configuración dentro de la imagen
COPY . /e2e/

# El entrypoint será configurado en docker-compose.yml
